# Generated by Django 3.0.10 on 2024-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='director_name',
            field=models.CharField(default='No director name available', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='name',
            field=models.CharField(default='No name availabel', max_length=256),
            preserve_default=False,
        ),
    ]
