# Generated by Django 3.0.10 on 2024-12-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0002_auto_20241221_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='director_name',
            field=models.CharField(default='No director name available', max_length=256),
        ),
        migrations.AlterField(
            model_name='poster',
            name='name',
            field=models.CharField(default='No name available', max_length=256),
        ),
    ]
