# Generated by Django 3.0.10 on 2024-12-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0003_auto_20241221_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='renderer.Poster')),
            ],
        ),
    ]
